### ISSUE TITLE
can this be use for a website?

### ISSUE THREAD

**Issue by daiky00** [Tlaster/AnimateRaw#1]
Hi, can I convert this to an anime site website like animecenter.tv? if so whats the best solution to do it? Thanks in advance.

**Comment by Tlaster** [comment]
Hello daiky00, sorry for the late response.
It is a website already, you can visit the [oneechan.moe](http://oneechan.moe/).
If you're looking for the source code, you can check out the [OneEchan.Server](https://github.com/Tlaster/OneEchan/tree/master/OneEchan.Server), it's using ASP.NET Core. 
And in order to actually 'run' the website, it will need a script to upload the anime automatically, you can check out the [OneEchan.Backend](https://github.com/Tlaster/OneEchan/tree/master/OneEchan.Backend), it's using .NET Core.
But the project do not provide the download part which is important because the script just checking a folder frequently and looking for the new which will be uploading, and add the information to the database, it can not download any anime, you need to do it yourself or use the torrent client.
Sorry for my poor English.
